### ISSUE TITLE
Ryzen 7 5800h Not working

### ISSUE THREAD

**Issue by Rxxbertx** [naveenkrdy/AmdTscSync#1]
hi, i think is not working 
![msg-1304303326-478227](https://github.com/naveenkrdy/AmdTscSync/assets/104899410/11ae7ceb-045c-460f-b6c5-86e230decf87)

**Comment by laris** [comment]
I got your tips from https://github.com/Seey6/CpuTscSync
5800U of my laptop Lenovo Yoga slim7
